version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "s3-notification-service"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-service-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dev"
s3_prefix = "s3-notification-service-dev"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = true
fail_on_empty_changeset = false

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-service-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-prod"
s3_prefix = "s3-notification-service-prod"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
fail_on_empty_changeset = false