AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Event-Driven Notification System

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)
  
  EmailSubscription:
    Type: String
    Description: Email address to receive notifications
  
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create

Resources:
  # S3 Bucket for file uploads
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt NotificationFunction.Arn
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda permission to allow S3 to invoke the function
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt NotificationFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${BucketName}

  # SNS Topic for email notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${Environment}-S3-Upload-Notifications'
      TopicName: !Sub '${Environment}-S3-Upload-Notifications'

  # Email subscription to the SNS topic
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref EmailSubscription

  # Lambda function for processing S3 events
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-s3-notification-function'
      CodeUri: src/handlers/
      Handler: notification_handler.lambda_handler
      Runtime: python3.1
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
          ENVIRONMENT: !Ref Environment
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: S3 Bucket for file uploads
    Value: !Ref UploadBucket
  
  NotificationTopicArn:
    Description: ARN of the SNS topic
    Value: !Ref NotificationTopic
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt NotificationFunction.Arn