name: Deploy SAM Application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.1'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Determine environment
        id: env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ENVIRONMENT="prod"
          else
            ENVIRONMENT="dev"
          fi
          echo "Environment set to: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Build SAM application
        run: |
          sam build --use-container

      - name: Deploy SAM application
        run: |
          ENVIRONMENT=${{ steps.env.outputs.environment }}
          
          # Load parameters from the appropriate environment file
          PARAMS=$(cat env/$ENVIRONMENT.json)
          
          # Deploy with SAM
          sam deploy \
            --config-env $ENVIRONMENT \
            --no-fail-on-empty-changeset \
            --parameter-overrides "Environment=$ENVIRONMENT $PARAMS"